#!/usr/bin/env bash
# script that displays numbers from 1 to 100
for e in {1..100}
do
	if [ $((e%15)) -eq 0 ]
	then
		echo "FizzBuzz"
	elif [ $((e%5)) -eq 0 ]
	then
		echo "Buzz"
	elif [ $((e%3)) -eq 0 ]
	then
		echo "Fizz"
	else
		echo $e
	fi
done
