#!/usr/bin/env bash
# show numbers from 1 to 20
imp=1
while [ $imp -le 20 ]
do
	echo $imp
	case $imp in
		4)
			echo "bad luck from China"
			;;
		9)
			echo "bad luck from Japan"
			;;
		17)
			echo "bad luck from Italy"
			;;
	esac
	((imp++))
done
