#!/usr/bin/env bash
# Show list directory, show format 
# display hours from 0 to 12
# display minutes from 1 to 59
a=0
e=1
while [ $a -le 12 ]
do
	echo "Hour: $a"
	while [ $e -le 59 ]
	do
		echo $e
		((e++))
	done
	((a++))
	((e=1))
done
